export const jeeAllCollege = [
  /* ================= IIT (23) ================= */
  { id: "IITB", fullName: "Indian Institute of Technology Bombay", shortName: "IIT Bombay", type: "IIT" },
  { id: "IITD", fullName: "Indian Institute of Technology Delhi", shortName: "IIT Delhi", type: "IIT" },
  { id: "IITM", fullName: "Indian Institute of Technology Madras", shortName: "IIT Madras", type: "IIT" },
  { id: "IITK", fullName: "Indian Institute of Technology Kanpur", shortName: "IIT Kanpur", type: "IIT" },
  { id: "IITKGP", fullName: "Indian Institute of Technology Kharagpur", shortName: "IIT Kharagpur", type: "IIT" },
  { id: "IITR", fullName: "Indian Institute of Technology Roorkee", shortName: "IIT Roorkee", type: "IIT" },
  { id: "IITG", fullName: "Indian Institute of Technology Guwahati", shortName: "IIT Guwahati", type: "IIT" },
  { id: "IITBHU", fullName: "Indian Institute of Technology (BHU) Varanasi", shortName: "IIT BHU", type: "IIT" },
  { id: "IITH", fullName: "Indian Institute of Technology Hyderabad", shortName: "IIT Hyderabad", type: "IIT" },
  { id: "IITISM", fullName: "Indian Institute of Technology (ISM) Dhanbad", shortName: "IIT Dhanbad", type: "IIT" },
  { id: "IITGN", fullName: "Indian Institute of Technology Gandhinagar", shortName: "IIT Gandhinagar", type: "IIT" },
  { id: "IITJ", fullName: "Indian Institute of Technology Jodhpur", shortName: "IIT Jodhpur", type: "IIT" },
  { id: "IITP", fullName: "Indian Institute of Technology Patna", shortName: "IIT Patna", type: "IIT" },
  { id: "IITRPR", fullName: "Indian Institute of Technology Ropar", shortName: "IIT Ropar", type: "IIT" },
  { id: "IITBBS", fullName: "Indian Institute of Technology Bhubaneswar", shortName: "IIT Bhubaneswar", type: "IIT" },
  { id: "IITIDR", fullName: "Indian Institute of Technology Indore", shortName: "IIT Indore", type: "IIT" },
  { id: "IITMDI", fullName: "Indian Institute of Technology Mandi", shortName: "IIT Mandi", type: "IIT" },
  { id: "IITPKD", fullName: "Indian Institute of Technology Palakkad", shortName: "IIT Palakkad", type: "IIT" },
  { id: "IITTP", fullName: "Indian Institute of Technology Tirupati", shortName: "IIT Tirupati", type: "IIT" },
  { id: "IITBH", fullName: "Indian Institute of Technology Bhilai", shortName: "IIT Bhilai", type: "IIT" },
  { id: "IITGOA", fullName: "Indian Institute of Technology Goa", shortName: "IIT Goa", type: "IIT" },
  { id: "IITJMU", fullName: "Indian Institute of Technology Jammu", shortName: "IIT Jammu", type: "IIT" },
  { id: "IITDH", fullName: "Indian Institute of Technology Dharwad", shortName: "IIT Dharwad", type: "IIT" },

  /* ================= NIT + IIEST (31) ================= */
  { id: "NITT", fullName: "National Institute of Technology Tiruchirappalli", shortName: "NIT Trichy", type: "NIT" },
  { id: "NITK", fullName: "National Institute of Technology Karnataka, Surathkal", shortName: "NIT Surathkal", type: "NIT" },
  { id: "NITW", fullName: "National Institute of Technology Warangal", shortName: "NIT Warangal", type: "NIT" },
  { id: "MNIT", fullName: "Malaviya National Institute of Technology Jaipur", shortName: "MNIT Jaipur", type: "NIT" },
  { id: "MANIT", fullName: "Maulana Azad National Institute of Technology Bhopal", shortName: "MANIT Bhopal", type: "NIT" },
  { id: "MNNIT", fullName: "Motilal Nehru National Institute of Technology Allahabad", shortName: "MNNIT Allahabad", type: "NIT" },
  { id: "SVNIT", fullName: "Sardar Vallabhbhai National Institute of Technology Surat", shortName: "SVNIT Surat", type: "NIT" },
  { id: "VNIT", fullName: "Visvesvaraya National Institute of Technology Nagpur", shortName: "VNIT Nagpur", type: "NIT" },
  { id: "NITR", fullName: "National Institute of Technology Rourkela", shortName: "NIT Rourkela", type: "NIT" },
  { id: "NITC", fullName: "National Institute of Technology Calicut", shortName: "NIT Calicut", type: "NIT" },
  { id: "NITDGP", fullName: "National Institute of Technology Durgapur", shortName: "NIT Durgapur", type: "NIT" },
  { id: "NITJ", fullName: "National Institute of Technology Jamshedpur", shortName: "NIT Jamshedpur", type: "NIT" },
  { id: "NITH", fullName: "National Institute of Technology Hamirpur", shortName: "NIT Hamirpur", type: "NIT" },
  { id: "NITP", fullName: "National Institute of Technology Patna", shortName: "NIT Patna", type: "NIT" },
  { id: "NITA", fullName: "National Institute of Technology Agartala", shortName: "NIT Agartala", type: "NIT" },
  { id: "NITS", fullName: "National Institute of Technology Silchar", shortName: "NIT Silchar", type: "NIT" },
  { id: "NITAP", fullName: "National Institute of Technology Andhra Pradesh", shortName: "NIT Andhra Pradesh", type: "NIT" },
  { id: "NITUK", fullName: "National Institute of Technology Uttarakhand", shortName: "NIT Uttarakhand", type: "NIT" },
  { id: "NITGOA", fullName: "National Institute of Technology Goa", shortName: "NIT Goa", type: "NIT" },
  { id: "NITDL", fullName: "National Institute of Technology Delhi", shortName: "NIT Delhi", type: "NIT" },
  { id: "NITMN", fullName: "National Institute of Technology Manipur", shortName: "NIT Manipur", type: "NIT" },
  { id: "NITMGH", fullName: "National Institute of Technology Meghalaya", shortName: "NIT Meghalaya", type: "NIT" },
  { id: "NITMZ", fullName: "National Institute of Technology Mizoram", shortName: "NIT Mizoram", type: "NIT" },
  { id: "NITNG", fullName: "National Institute of Technology Nagaland", shortName: "NIT Nagaland", type: "NIT" },
  { id: "NITPY", fullName: "National Institute of Technology Puducherry", shortName: "NIT Puducherry", type: "NIT" },
  { id: "NITRR", fullName: "National Institute of Technology Raipur", shortName: "NIT Raipur", type: "NIT" },
  { id: "NITSK", fullName: "National Institute of Technology Sikkim", shortName: "NIT Sikkim", type: "NIT" },
  { id: "NITSR", fullName: "National Institute of Technology Srinagar", shortName: "NIT Srinagar", type: "NIT" },
  { id: "NITJSR", fullName: "National Institute of Technology Jamshedpur", shortName: "NIT Jamshedpur", type: "NIT" },
  { id: "IIEST", fullName: "Indian Institute of Engineering Science and Technology, Shibpur", shortName: "IIEST Shibpur", type: "NIT" },
  { id: "NITAGARTALA", fullName: "National Institute of Technology Agartala", shortName: "NIT Agartala", type: "NIT" },

  /* ================= IIIT (26) ================= */
  { id: "IIITA", fullName: "Indian Institute of Information Technology Allahabad", shortName: "IIIT Allahabad", type: "IIIT" },
  { id: "IIITH", fullName: "International Institute of Information Technology Hyderabad", shortName: "IIIT Hyderabad", type: "IIIT" },
  { id: "ABVIIITM", fullName: "Atal Bihari Vajpayee Indian Institute of Information Technology and Management Gwalior", shortName: "ABV IIITM Gwalior", type: "IIIT" },
  { id: "IIITL", fullName: "Indian Institute of Information Technology Lucknow", shortName: "IIIT Lucknow", type: "IIIT" },
  { id: "IIITDMJ", fullName: "PDPM Indian Institute of Information Technology, Design and Manufacturing Jabalpur", shortName: "IIITDM Jabalpur", type: "IIIT" },
  { id: "IIITDMK", fullName: "Indian Institute of Information Technology Design and Manufacturing Kancheepuram", shortName: "IIITDM Kancheepuram", type: "IIIT" },
  { id: "IIITK", fullName: "Indian Institute of Information Technology Kota", shortName: "IIIT Kota", type: "IIIT" },
  { id: "IIITN", fullName: "Indian Institute of Information Technology Nagpur", shortName: "IIIT Nagpur", type: "IIIT" },
  { id: "IIITP", fullName: "Indian Institute of Information Technology Pune", shortName: "IIIT Pune", type: "IIIT" },
  { id: "IIITBGP", fullName: "Indian Institute of Information Technology Bhagalpur", shortName: "IIIT Bhagalpur", type: "IIIT" },
  { id: "IIITR", fullName: "Indian Institute of Information Technology Ranchi", shortName: "IIIT Ranchi", type: "IIIT" },
  { id: "IIITS", fullName: "Indian Institute of Information Technology Sri City", shortName: "IIIT Sri City", type: "IIIT" },
  { id: "IIITV", fullName: "Indian Institute of Information Technology Vadodara", shortName: "IIIT Vadodara", type: "IIIT" },
  { id: "IIITKLY", fullName: "Indian Institute of Information Technology Kalyani", shortName: "IIIT Kalyani", type: "IIIT" },
  { id: "IIITUNA", fullName: "Indian Institute of Information Technology Una", shortName: "IIIT Una", type: "IIIT" },
  { id: "IIITKRM", fullName: "Indian Institute of Information Technology Kurnool", shortName: "IIIT Kurnool", type: "IIIT" },
  { id: "IIITKTY", fullName: "Indian Institute of Information Technology Kottayam", shortName: "IIIT Kottayam", type: "IIIT" },
  { id: "IIITMNP", fullName: "Indian Institute of Information Technology Manipur", shortName: "IIIT Manipur", type: "IIIT" },
  { id: "IIITNGR", fullName: "Indian Institute of Information Technology Naya Raipur", shortName: "IIIT Naya Raipur", type: "IIIT" },
  { id: "IIITPN", fullName: "Indian Institute of Information Technology Pune", shortName: "IIIT Pune", type: "IIIT" },
  { id: "IIITRCH", fullName: "Indian Institute of Information Technology Raichur", shortName: "IIIT Raichur", type: "IIIT" },
  { id: "IIITSR", fullName: "Indian Institute of Information Technology Srirangam", shortName: "IIIT Srirangam", type: "IIIT" },
  { id: "IIITDWD", fullName: "Indian Institute of Information Technology Dharwad", shortName: "IIIT Dharwad", type: "IIIT" },
  { id: "IIITBPL", fullName: "Indian Institute of Information Technology Bhopal", shortName: "IIIT Bhopal", type: "IIIT" },
  { id: "IIITSRT", fullName: "Indian Institute of Information Technology Surat", shortName: "IIIT Surat", type: "IIIT" },
  { id: "IIITAGT", fullName: "Indian Institute of Information Technology Agartala", shortName: "IIIT Agartala", type: "IIIT" },

  /* ================= GFTI (48) ================= */
  { id: "BITM", fullName: "Birla Institute of Technology, Mesra", shortName: "BIT Mesra", type: "GFTI" },
  { id: "PEC", fullName: "Punjab Engineering College, Chandigarh", shortName: "PEC Chandigarh", type: "GFTI" },
  { id: "SLIET", fullName: "Sant Longowal Institute of Engineering and Technology", shortName: "SLIET Longowal", type: "GFTI" },
  { id: "IITRAM", fullName: "Institute of Infrastructure Technology Research and Management Ahmedabad", shortName: "IITRAM", type: "GFTI" },
  { id: "AUS", fullName: "Assam University Silchar", shortName: "Assam University", type: "GFTI" },
  { id: "NITAMT", fullName: "National Institute of Advanced Manufacturing Technology Ranchi", shortName: "NIAMT Ranchi", type: "GFTI" },
  { id: "IICT", fullName: "Indian Institute of Carpet Technology Bhadohi", shortName: "IICT Bhadohi", type: "GFTI" },
  { id: "NIFTEM", fullName: "National Institute of Food Technology Entrepreneurship and Management Sonipat", shortName: "NIFTEM Sonipat", type: "GFTI" },
  { id: "GGV", fullName: "Guru Ghasidas Vishwavidyalaya Bilaspur", shortName: "GGV Bilaspur", type: "GFTI" },
  { id: "CUJ", fullName: "Central University of Jharkhand", shortName: "CU Jharkhand", type: "GFTI" },
  { id: "CUH", fullName: "Central University of Haryana", shortName: "CU Haryana", type: "GFTI" },
  { id: "CURAJ", fullName: "Central University of Rajasthan", shortName: "CU Rajasthan", type: "GFTI" },
  { id: "SMVDU", fullName: "Shri Mata Vaishno Devi University", shortName: "SMVDU", type: "GFTI" },
  { id: "NEHU", fullName: "North Eastern Hill University", shortName: "NEHU", type: "GFTI" },
  { id: "CITK", fullName: "Central Institute of Technology Kokrajhar", shortName: "CIT Kokrajhar", type: "GFTI" },
  { id: "SPADEL", fullName: "School of Planning and Architecture New Delhi", shortName: "SPA Delhi", type: "GFTI" },
  { id: "SPABPL", fullName: "School of Planning and Architecture Bhopal", shortName: "SPA Bhopal", type: "GFTI" },
  { id: "SPAVJA", fullName: "School of Planning and Architecture Vijayawada", shortName: "SPA Vijayawada", type: "GFTI" },
  { id: "NERIST", fullName: "North Eastern Regional Institute of Science and Technology", shortName: "NERIST", type: "GFTI" },
  { id: "GSIVT", fullName: "Gati Shakti Vishwavidyalaya Vadodara", shortName: "GSV Vadodara", type: "GFTI" },
  { id: "SGGS", fullName: "Shri Guru Gobind Singhji Institute of Engineering and Technology Nanded", shortName: "SGGS Nanded", type: "GFTI" },
  { id: "FET", fullName: "Faculty of Engineering and Technology, University of Lucknow", shortName: "FET Lucknow", type: "GFTI" },
  { id: "JMI", fullName: "Jamia Millia Islamia, New Delhi", shortName: "Jamia Millia Islamia", type: "GFTI" },
  { id: "DTU", fullName: "Delhi Technological University", shortName: "DTU", type: "GFTI" },
  { id: "NSUT", fullName: "Netaji Subhas University of Technology", shortName: "NSUT", type: "GFTI" },
  { id: "IGDTUW", fullName: "Indira Gandhi Delhi Technical University for Women", shortName: "IGDTUW", type: "GFTI" },
  { id: "BPUT", fullName: "Biju Patnaik University of Technology, Rourkela", shortName: "BPUT", type: "GFTI" },
  { id: "JUIT", fullName: "Jaypee University of Information Technology, Solan", shortName: "JUIT", type: "GFTI" },
  { id: "UPES", fullName: "University of Petroleum and Energy Studies, Dehradun", shortName: "UPES", type: "GFTI" },
  { id: "SGSITS", fullName: "Shri Govindram Seksaria Institute of Technology and Science, Indore", shortName: "SGSITS", type: "GFTI" },
  { id: "LNMIIT", fullName: "The LNM Institute of Information Technology, Jaipur", shortName: "LNMIIT", type: "GFTI" },
  { id: "DAIICT", fullName: "Dhirubhai Ambani Institute of Information and Communication Technology, Gandhinagar", shortName: "DAIICT", type: "GFTI" },
  { id: "PDM", fullName: "PDM University, Bahadurgarh", shortName: "PDM University", type: "GFTI" },
  { id: "MAKAUT", fullName: "Maulana Abul Kalam Azad University of Technology, Kolkata", shortName: "MAKAUT", type: "GFTI" },
  { id: "AU", fullName: "University of Allahabad", shortName: "AU Allahabad", type: "GFTI" },
  { id: "BIT", fullName: "Bengal Institute of Technology, Kolkata", shortName: "BIT Kolkata", type: "GFTI" },
  { id: "HBTU", fullName: "Harcourt Butler Technical University, Kanpur", shortName: "HBTU", type: "GFTI" },
  { id: "KNIT", fullName: "Kamla Nehru Institute of Technology, Sultanpur", shortName: "KNIT", type: "GFTI" },
  { id: "MITS", fullName: "Madanapalle Institute of Technology and Science", shortName: "MITS", type: "GFTI" },
  { id: "MU", fullName: "University of Mumbai", shortName: "Mumbai University", type: "GFTI" },
  { id: "NITTE", fullName: "NITTE Meenakshi Institute of Technology, Bangalore", shortName: "NITTE", type: "GFTI" },
  { id: "PSG", fullName: "PSG College of Technology, Coimbatore", shortName: "PSG Tech", type: "GFTI" },
  { id: "RCCIIT", fullName: "RCC Institute of Information Technology, Kolkata", shortName: "RCCIIT", type: "GFTI" },
  { id: "RVCE", fullName: "R.V. College of Engineering, Bangalore", shortName: "RVCE", type: "GFTI" },
  { id: "SASTRA", fullName: "SASTRA Deemed University, Thanjavur", shortName: "SASTRA", type: "GFTI" },
  { id: "SIT", fullName: "Symbiosis Institute of Technology, Pune", shortName: "SIT", type: "GFTI" },
  { id: "SRM", fullName: "SRM Institute of Science and Technology, Chennai", shortName: "SRM", type: "GFTI" },
  { id: "VIT", fullName: "Vellore Institute of Technology, Vellore", shortName: "VIT", type: "GFTI" }
];

 export const AllCouncilling = [
  { id: "JOSAA", name: "JoSAA (Joint Seat Allocation Authority)", type: "National", exams: ["JEE MAIN", "JEE ADVANCED"] },
  { id: "CSAB", name: "CSAB (Central Seat Allocation Board)", type: "National", exams: ["JEE MAIN"] },
  { id: "CUET", name: "CUET (Common University Entrance Test)", type: "National", exams: ["CUET UG"] },
  // { id: "NEST", name: "NEST (National Entrance Screening Test)", type: "National", exams: ["NEST"] },
  // { id: "KVPY", name: "KVPY (Kishore Vaigyanik Protsahan Yojana)", type: "National", exams: ["KVPY"] },
  { id: "IIT JAM", name: "IIT JAM", type: "National", exams: ["IIT JAM"] },
  { id: "GATE", name: "GATE (Graduate Aptitude Test in Engineering)", type: "National", exams: ["GATE"] },
  // { id: "NIMCET", name: "NIMCET (NIT MCA Common Entrance Test)", type: "National", exams: ["NIMCET"] },
  // { id: "TANCET", name: "TANCET (Tamil Nadu Common Entrance Test)", type: "State", exams: ["TANCET"] },
  // { id: "MHTCET", name: "MHT CET (Maharashtra Common Entrance Test)", type: "State", exams: ["MHT CET"] },
  // { id: "KEAM", name: "KEAM (Kerala Engineering Architecture Medical)", type: "State", exams: ["KEAM"] },
  { id: "WBJEE", name: "WBJEE (West Bengal Joint Entrance Examination)", type: "State", exams: ["WBJEE"] },
  // { id: "UPSEE", name: "UPSEE (Uttar Pradesh State Entrance Exam)", type: "State", exams: ["UPSEE"] },
  // { id: "TS EAMCET", name: "TS EAMCET (Telangana State Engineering, Agriculture & Medical Common Entrance Test)", type: "State", exams: ["TS EAMCET"] },
  // { id: "AP EAMCET", name: "AP EAMCET (Andhra Pradesh EAMCET)", type: "State", exams: ["AP EAMCET"] },
  // { id: "JAC", name: "JAC (Joint Admission Counselling, Delhi)", type: "State", exams: ["JAC Delhi"] },
  // { id: "COMEDK", name: "COMEDK UGET", type: "State", exams: ["COMEDK UGET"] },
  // { id: "KCET", name: "KCET (Karnataka Common Entrance Test)", type: "State", exams: ["KCET"] },
  // { id: "HSSC", name: "Haryana State Counselling", type: "State", exams: ["Haryana CET"] },
  // { id: "APLAWCET", name: "APLAWCET", type: "State", exams: ["APLAWCET"] },
  // { id: "TS LAWCET", name: "TS LAWCET", type: "State", exams: ["TS LAWCET"] }
];
